import React, { useState } from 'react';
import { Question } from '../types/scratch';
import { Plus, Trash2, RotateCcw, Sparkles, BookOpen, Layers, CheckCircle, Loader2, Wand2, AlertCircle } from 'lucide-react';
import { sound } from '../utils/audio';

interface DeckBuilderProps {
  questions: Question[];
  onAddQuestion: (q: Question) => void;
  onRemoveQuestion: (id: string) => void;
  onResetDefault: () => void;
  onLoadPreset: (presetKey: 'standard' | 'advanced' | 'cs') => void;
  onBatchUpdateQuestions: (newQuestions: Question[], replace?: boolean) => void;
}

export const DeckBuilder: React.FC<DeckBuilderProps> = ({
  questions,
  onAddQuestion,
  onRemoveQuestion,
  onResetDefault,
  onLoadPreset,
  onBatchUpdateQuestions,
}) => {
  // Manual Question Form State
  const [isAdding, setIsAdding] = useState(false);
  const [questionText, setQuestionText] = useState('');
  const [correctAnswer, setCorrectAnswer] = useState('');
  const [acceptedAliases, setAcceptedAliases] = useState('');
  const [correctSayText, setCorrectSayText] = useState('Correct! Great job!');
  const [incorrectSayText, setIncorrectSayText] = useState('');
  const [topic, setTopic] = useState('Python Fundamentals');
  const [explanation, setExplanation] = useState('');

  // Gemini AI Generation State
  const [aiTopic, setAiTopic] = useState('');
  const [cardCount, setCardCount] = useState<number>(3);
  const [replaceExisting, setReplaceExisting] = useState<boolean>(true);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const [aiSuccessMessage, setAiSuccessMessage] = useState<string | null>(null);

  // Suggested Topics for quick testing
  const SUGGESTED_TOPICS = [
    'Python OOP & Classes',
    'Recursion & Algorithms',
    'Python File I/O & Exceptions',
    'Data Structures & Stacks',
    'Boolean Logic & Bitwise Ops',
  ];

  // Gemini AI Deck Generation Handler
  const handleGenerateWithGemini = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!aiTopic.trim()) return;

    setIsGenerating(true);
    setAiError(null);
    setAiSuccessMessage(null);
    sound.playPop();

    try {
      const response = await fetch('/api/generate-deck', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: aiTopic.trim(),
          count: cardCount,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate flashcards via Gemini API.');
      }

      if (!data.cards || !Array.isArray(data.cards) || data.cards.length === 0) {
        throw new Error('Gemini API did not return any flashcards.');
      }

      // Convert generated cards into our standard Question schema
      const startingNum = replaceExisting ? 1 : questions.length + 1;

      interface GeneratedCard {
        questionText: string;
        correctAnswer: string;
        acceptedAliases?: string[];
        correctSayText?: string;
        incorrectSayText?: string;
        topic?: string;
        explanation?: string;
      }

      const formattedQuestions: Question[] = data.cards.map((card: GeneratedCard, idx: number) => {
        const qNum = startingNum + idx;
        const qText = card.questionText.trim();
        const cleanText = qText.match(/^Q\d+:\s*/i) ? qText : `Q${qNum}: ${qText}`;
        const answer = card.correctAnswer.trim();
        const aliases = Array.isArray(card.acceptedAliases)
          ? card.acceptedAliases.map((a: string) => a.toLowerCase().trim()).filter(Boolean)
          : [];

        if (!aliases.includes(answer.toLowerCase())) {
          aliases.push(answer.toLowerCase());
        }

        return {
          id: `ai_${Date.now()}_${idx}`,
          questionNumber: qNum,
          questionText: cleanText,
          correctAnswer: answer,
          acceptedAliases: aliases,
          correctSayText: card.correctSayText || 'Correct! Outstanding reasoning!',
          incorrectSayText: card.incorrectSayText || `Incorrect. The correct answer is '${answer}'.`,
          topic: card.topic || aiTopic.trim(),
          explanation: card.explanation || `Concept generated by Gemini for topic: ${aiTopic.trim()}`,
        };
      });

      // Update question state
      onBatchUpdateQuestions(formattedQuestions, replaceExisting);
      sound.playCorrect();
      setAiSuccessMessage(
        `Generated and stored ${formattedQuestions.length} Scratch flashcards on "${aiTopic.trim()}" in questions state!`
      );
      setAiTopic('');
    } catch (err: unknown) {
      sound.playIncorrect();
      const message = err instanceof Error ? err.message : 'Unknown generation error';
      setAiError(message);
    } finally {
      setIsGenerating(false);
    }
  };

  // Manual Question Addition
  const handleCreateManual = (e: React.FormEvent) => {
    e.preventDefault();
    if (!questionText.trim() || !correctAnswer.trim()) return;

    sound.playCorrect();
    const nextNum = questions.length + 1;
    const aliases = acceptedAliases
      .split(',')
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean);

    if (!aliases.includes(correctAnswer.trim().toLowerCase())) {
      aliases.push(correctAnswer.trim().toLowerCase());
    }

    const newQ: Question = {
      id: `custom_${Date.now()}`,
      questionNumber: nextNum,
      questionText: questionText.startsWith(`Q${nextNum}:`) ? questionText : `Q${nextNum}: ${questionText}`,
      correctAnswer: correctAnswer.trim(),
      acceptedAliases: aliases,
      correctSayText: correctSayText || 'Correct! Great job!',
      incorrectSayText: incorrectSayText || `Incorrect. The correct answer is '${correctAnswer.trim()}'.`,
      topic: topic || 'Python Concepts',
      explanation: explanation || 'Custom question block added through modular deck architecture.',
    };

    onAddQuestion(newQ);
    setIsAdding(false);
    // Reset form
    setQuestionText('');
    setCorrectAnswer('');
    setAcceptedAliases('');
    setCorrectSayText('Correct! Great job!');
    setIncorrectSayText('');
    setTopic('Python Fundamentals');
    setExplanation('');
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl text-slate-100 space-y-6">
      {/* Header and Modular Concept Callout */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-emerald-400">
              Lab Presentation · Modular Design Step
            </span>
            <span className="text-xs text-slate-500">·</span>
            <span className="text-xs text-slate-400">AI-Powered Deck Engine</span>
          </div>
          <h2 className="text-lg font-bold text-slate-100 mt-1">
            Dynamic Flashcard Deck & Question Injector
          </h2>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl leading-relaxed">
            Generate custom flashcard decks automatically using the <strong>Gemini API</strong>, or manually
            add questions to demonstrate how the Scratch block stack dynamically updates without code changes.
          </p>
        </div>

        {/* Preset Decks Actions */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => {
              sound.playPop();
              onLoadPreset('standard');
            }}
            className="px-3 py-1.5 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors"
          >
            Standard Deck (3 Qs)
          </button>
          <button
            onClick={() => {
              sound.playPop();
              onLoadPreset('advanced');
            }}
            className="px-3 py-1.5 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors"
          >
            Advanced Deck (5 Qs)
          </button>
          <button
            onClick={() => {
              sound.playPop();
              onResetDefault();
            }}
            title="Reset to default prompt questions"
            className="p-1.5 text-xs text-slate-400 hover:text-rose-400 bg-slate-950 hover:bg-slate-800 rounded-lg transition-colors"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* ========================================================================
          GEMINI API AUTOMATIC FLASHCARD GENERATION PANEL
          ======================================================================== */}
      <div className="bg-slate-950 border-2 border-indigo-500/40 rounded-xl p-5 shadow-lg space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-slate-800/80">
          <div className="flex items-center gap-2">
            <Wand2 className="w-4 h-4 text-indigo-400" />
            <h3 className="text-sm font-bold text-slate-100">
              Generate Flashcard Deck with Gemini AI
            </h3>
            <span className="text-[10px] bg-indigo-500/20 text-indigo-300 font-mono px-2 py-0.5 rounded border border-indigo-500/30">
              gemini-3.8-flash
            </span>
          </div>
          <span className="text-xs text-slate-400">
            Automatically populates questions, answers, and explanations
          </span>
        </div>

        <form onSubmit={handleGenerateWithGemini} className="space-y-3">
          <div className="flex flex-col sm:flex-row gap-3">
            {/* Topic Input Field */}
            <div className="flex-1">
              <input
                type="text"
                value={aiTopic}
                onChange={(e) => setAiTopic(e.target.value)}
                placeholder="Enter study topic (e.g. Python Object-Oriented Programming, SQL, Binary Trees)..."
                disabled={isGenerating}
                className="w-full px-3.5 py-2.5 text-xs sm:text-sm bg-slate-900 border border-slate-700 rounded-lg text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-400 focus:ring-1 focus:ring-indigo-400 transition-colors"
              />
            </div>

            {/* Card Count Selector */}
            <div className="flex items-center gap-2 shrink-0">
              <label className="text-xs text-slate-400">Count:</label>
              <select
                value={cardCount}
                onChange={(e) => setCardCount(Number(e.target.value))}
                disabled={isGenerating}
                className="px-2.5 py-2.5 text-xs bg-slate-900 border border-slate-700 rounded-lg text-slate-200 focus:outline-none focus:border-indigo-400"
              >
                <option value={2}>2 Cards</option>
                <option value={3}>3 Cards</option>
                <option value={4}>4 Cards</option>
                <option value={5}>5 Cards</option>
              </select>
            </div>

            {/* Mode: Replace or Append */}
            <div className="flex items-center gap-1.5 shrink-0 bg-slate-900 border border-slate-700/80 rounded-lg p-1 text-xs">
              <button
                type="button"
                onClick={() => setReplaceExisting(true)}
                className={`px-2.5 py-1.5 rounded transition-colors ${
                  replaceExisting ? 'bg-indigo-600 text-white font-medium shadow-sm' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                New Deck
              </button>
              <button
                type="button"
                onClick={() => setReplaceExisting(false)}
                className={`px-2.5 py-1.5 rounded transition-colors ${
                  !replaceExisting ? 'bg-indigo-600 text-white font-medium shadow-sm' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Append
              </button>
            </div>

            {/* Generate Action Button */}
            <button
              type="submit"
              disabled={isGenerating || !aiTopic.trim()}
              className="px-4 py-2.5 text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:pointer-events-none rounded-lg shadow transition-all flex items-center justify-center gap-2 shrink-0 active:scale-95"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Synthesizing...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-amber-300" />
                  <span>Generate Cards</span>
                </>
              )}
            </button>
          </div>

          {/* Quick Suggestions Chips */}
          <div className="flex flex-wrap items-center gap-1.5 pt-1 text-xs">
            <span className="text-slate-500 text-[11px] mr-1">Suggestions:</span>
            {SUGGESTED_TOPICS.map((suggested) => (
              <button
                key={suggested}
                type="button"
                onClick={() => {
                  sound.playPop();
                  setAiTopic(suggested);
                }}
                disabled={isGenerating}
                className="px-2 py-0.5 rounded text-[11px] bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700/60 transition-colors"
              >
                {suggested}
              </button>
            ))}
          </div>

          {/* Error Message */}
          {aiError && (
            <div className="p-3 bg-rose-950/40 border border-rose-500/50 rounded-lg text-xs text-rose-300 flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
              <div>
                <strong>Generation Error:</strong> {aiError}
              </div>
            </div>
          )}

          {/* Success Banner */}
          {aiSuccessMessage && (
            <div className="p-3 bg-emerald-950/40 border border-emerald-500/50 rounded-lg text-xs text-emerald-300 flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>{aiSuccessMessage}</span>
            </div>
          )}
        </form>
      </div>

      {/* Active Question Cards Grid */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-300">
            Active Study Deck ({questions.length} Cards in State)
          </span>
          <button
            onClick={() => {
              sound.playPop();
              setIsAdding(!isAdding);
            }}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg shadow-sm transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Manual Question Block</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {questions.map((q, idx) => (
            <div
              key={q.id}
              className="bg-slate-950/80 border border-slate-800 rounded-lg p-3.5 flex flex-col justify-between hover:border-slate-700 transition-colors relative group"
            >
              <div>
                <div className="flex items-center justify-between text-[11px] mb-1.5">
                  <span className="font-mono text-cyan-400 font-semibold">Q{idx + 1}</span>
                  <span className="text-slate-400 truncate max-w-[120px]">{q.topic}</span>
                </div>
                <h4 className="text-xs font-medium text-slate-200 line-clamp-2 mb-2">
                  {q.questionText}
                </h4>
                <div className="bg-slate-900 border border-slate-800/80 rounded px-2 py-1 text-[11px] flex items-center justify-between mb-2">
                  <span className="text-slate-400">Accepted Answer:</span>
                  <span className="font-mono font-bold text-amber-400">{q.correctAnswer}</span>
                </div>
                {q.acceptedAliases && q.acceptedAliases.length > 1 && (
                  <div className="text-[10px] text-slate-400 mb-2 truncate">
                    <span>Aliases: </span>
                    <span className="font-mono text-slate-300">{q.acceptedAliases.join(', ')}</span>
                  </div>
                )}
                <p className="text-[11px] text-slate-400 line-clamp-2 italic">
                  "{q.explanation}"
                </p>
              </div>

              <div className="mt-3 pt-2 border-t border-slate-800/80 flex items-center justify-between">
                <span className="text-[10px] text-emerald-400 font-medium flex items-center gap-1">
                  <CheckCircle className="w-3 h-3" />
                  <span>+1 Score Increment</span>
                </span>
                {questions.length > 1 && (
                  <button
                    onClick={() => {
                      sound.playPop();
                      onRemoveQuestion(q.id);
                    }}
                    title="Remove question block"
                    className="text-slate-500 hover:text-rose-400 p-1 rounded transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Add New Question Manual Modal/Drawer Form */}
      {isAdding && (
        <form
          onSubmit={handleCreateManual}
          className="bg-slate-950 border-2 border-emerald-500/40 rounded-xl p-5 shadow-2xl space-y-4 animate-in slide-in-from-top-4 duration-200"
        >
          <div className="flex items-center justify-between pb-2 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              <h3 className="text-sm font-semibold text-slate-100">
                Manual Scratch Question Block Generator (Q{questions.length + 1})
              </h3>
            </div>
            <button
              type="button"
              onClick={() => setIsAdding(false)}
              className="text-xs text-slate-400 hover:text-slate-200"
            >
              Cancel
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Question Text (ask & wait string) *
              </label>
              <input
                type="text"
                required
                value={questionText}
                onChange={(e) => setQuestionText(e.target.value)}
                placeholder="e.g. Which keyword imports a library in Python?"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Correct Answer (exact check) *
              </label>
              <input
                type="text"
                required
                value={correctAnswer}
                onChange={(e) => setCorrectAnswer(e.target.value)}
                placeholder="e.g. import"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Accepted Aliases (comma separated)
              </label>
              <input
                type="text"
                value={acceptedAliases}
                onChange={(e) => setAcceptedAliases(e.target.value)}
                placeholder="e.g. import, from...import, imports"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Topic / Subject Area
              </label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Modules & Packages"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Affirmative Host Feedback
              </label>
              <input
                type="text"
                value={correctSayText}
                onChange={(e) => setCorrectSayText(e.target.value)}
                placeholder="e.g. Correct! Spot on!"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">
                Conceptual Explanation (for Viva & Review)
              </label>
              <input
                type="text"
                value={explanation}
                onChange={(e) => setExplanation(e.target.value)}
                placeholder="e.g. The import statement binds module symbols to current scope."
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded text-xs text-slate-100 focus:ring-1 focus:ring-emerald-500 outline-none"
              />
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setIsAdding(false)}
              className="px-4 py-2 text-xs font-medium text-slate-400 hover:text-slate-200"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg shadow transition-colors"
            >
              Inject Block Into Scratch Script
            </button>
          </div>
        </form>
      )}
    </div>
  );
};
